Fixed some variables/tasks to allow upgrade correctly
idealista/clickhouse_role pull request #31
Opened 2022-08-26 10:23 UTC by lpeman

### Description of the Change

- Update deb repository to upgrade to new versions
- Change in handles tasks systemd to service command
- Remove clickhouse-server.service template 

### Benefits
Upgrade clickhouse version 
### Applicable Issues

Resolves https://github.com/idealista/clickhouse_role/issues/30

2022-08-29 08:56 UTC, amanzanotejon approved these changes

2022-08-30 08:27 UTC, jmonterrubio approved these changes

2022-08-30 08:35 UTC, Plozano94 approved these changes

2022-08-30 09:23 UTC, ultraheroe requested changes
Don't forget to update the changelog! 😉

2022-08-30 09:23 UTC, ultraheroe commented on templates/clickhouse-server.service.j2
> -{{ ansible_managed | comment }}
For maintaining the same behavior till now, I would prefer to make the necessary changes than delete and use the default (with no option to customize) service file.

It's seems that we only had to update some lines from the service file like CapabilityBoundingSet and maybe the After and Wants lines like in here https://github.com/ClickHouse/ClickHouse/blob/b4b603e0b57bdd1ce373ca278b21a7267ffff2ee/packages/clickhouse-server.service

2022-08-30 09:23 UTC, ultraheroe commented on tasks/service-clickhouse.yml
> +- name: CLICKHOUSE | Remove file (delete file if exists)
If we update the service template with the new settings this change isn't necessary

2022-08-30 14:05 UTC, ultraheroe approved these changes

2022-08-30 14:05 UTC, ultraheroe commented on defaults/main.yml
> -clickhouse_service_template_path: clickhouse-server.service.j2
I think this var may stay for service config, as is used in the _CLICKHOUSE | Copy systemd unit configuration file_ task

2022-08-30 14:05 UTC, ultraheroe commented on tasks/service-clickhouse.yml
> +- name: CLICKHOUSE | Remove file (delete file if exists)
solved by @lpeman

2022-08-30 14:05 UTC, ultraheroe commented on templates/clickhouse-server.service.j2
> -{{ ansible_managed | comment }}
solved by @lpeman

2022-08-31 07:57 UTC, merged